use v6.d;

# TreeSitter::Native::Types — enumerations and the typed query failure.
#
# Deliberately NOT a `unit module`. Two reasons:
#
#   1. X::TreeSitter::Query has to land in the global namespace. A
#      nested-name class declared inside `unit module Foo` nests under
#      it — `class X::TreeSitter::Query` inside `unit module
#      TreeSitter::Native::Types` would really be
#      TreeSitter::Native::Types::X::TreeSitter::Query, which is what
#      .^name, .WHAT.gist and every `when` clause would show.
#   2. Exception families are declared as plain global classes, never
#      with `is export`: `is export` on a nested-name class exports the
#      LEAF name too, so two dists exporting an X::…::Query could not be
#      imported together.
#
# The enums do carry `is export`, which is what makes their UPPER_CASE
# values visible to importers.

#| Why C<ts_query_new> refused a query, mirrored from tree-sitter's
#| C<TSQueryError>. Values 0..6 are tree-sitter's own and arrive
#| through the shim's C<out_error_type> out-param verbatim.
#|
#| C<QUERY_ERROR_PREDICATE> is the one addition, and it is never
#| produced by tree-sitter: the C library parses predicates but leaves
#| their meaning entirely to bindings, so a query naming a predicate
#| this binding cannot evaluate — or handing one the wrong number of
#| arguments — compiles cleanly at the C level and is rejected a moment
#| later by L<TreeSitter::Native::Query>. It needs a kind of its own so
#| that C<when> chains can tell "your query is not valid tree-sitter"
#| apart from "your query is valid but I cannot honour it".
#|
#|     use TreeSitter::Native::Types;
#|
#|     say QUERY_ERROR_NODE_TYPE.value;   # 2
#|     say QUERY_ERROR_NODE_TYPE.key;     # QUERY_ERROR_NODE_TYPE
#|
#|     CATCH {
#|         when X::TreeSitter::Query {
#|             given .kind {
#|                 when QUERY_ERROR_NODE_TYPE { note "no such node type" }
#|                 when QUERY_ERROR_PREDICATE { note "unsupported #…?" }
#|                 default                    { note .message }
#|             }
#|         }
#|     }
enum QueryErrorKind is export (
    QUERY_ERROR_NONE      => 0,
    QUERY_ERROR_SYNTAX    => 1,
    QUERY_ERROR_NODE_TYPE => 2,
    QUERY_ERROR_FIELD     => 3,
    QUERY_ERROR_CAPTURE   => 4,
    QUERY_ERROR_STRUCTURE => 5,
    QUERY_ERROR_LANGUAGE  => 6,
    QUERY_ERROR_PREDICATE => 7,
);

#| The three kinds of predicate step tree-sitter reports, mirrored from
#| C<TSQueryPredicateStepType>. C<PREDICATE_STEP_DONE> terminates one
#| predicate within a pattern's step list; the other two say whether a
#| step's C<value_id> indexes the query's capture table or its string
#| table.
#|
#| L<TreeSitter::Native::Query> consumes the raw steps at construction
#| time and hands back
#| L<TreeSitter::Native::Query::Predicate|TreeSitter::Native::Query>
#| objects whose arguments carry one of these as their C<.kind>:
#|
#|     my $q = Query.new('javascript', '(call_expression
#|         function: (identifier) @name) @ref
#|         (#not-match? @name "^(require)$")');
#|
#|     for $q.pattern-predicates(0)[0].args -> $arg {
#|         say $arg.kind, ' ', $arg.value;
#|     }
#|     # PREDICATE_STEP_CAPTURE name
#|     # PREDICATE_STEP_STRING ^(require)$
enum PredicateStepType is export (
    PREDICATE_STEP_DONE    => 0,
    PREDICATE_STEP_CAPTURE => 1,
    PREDICATE_STEP_STRING  => 2,
);

#| tree-sitter's C<TSSymbolType>, describing what a grammar symbol id
#| stands for. Provided for completeness and for consumers that read
#| symbol ids off nodes (C<Node.symbol>) and want to talk about them in
#| words; the v1 shim does not wrap C<ts_language_symbol_type>, so
#| nothing in this distribution returns one of these values yet.
#|
#| The ordering is tree-sitter's, not ours, and is part of the C ABI:
#| regular (a named rule), anonymous (a literal token such as C<"+">),
#| supertype (a hidden rule other rules are grouped under), auxiliary
#| (generated by the parser generator itself).
enum SymbolType is export (
    SYMBOL_TYPE_REGULAR   => 0,
    SYMBOL_TYPE_ANONYMOUS => 1,
    SYMBOL_TYPE_SUPERTYPE => 2,
    SYMBOL_TYPE_AUXILIARY => 3,
);

#| tree-sitter's C<TSInputEncoding>. This distribution parses UTF-8 and
#| nothing else — C<INPUT_ENCODING_UTF8> is the only value any call
#| here will ever use — but the enum is spelled out so that the byte
#| doctrine has a name to point at, and so a later release that wraps
#| the streaming C<TSInput> interface does not have to invent one.
#|
#| Every offset this distribution produces or consumes (C<start-byte>,
#| C<end-byte>, point columns, query error offsets, query byte ranges)
#| is a byte offset into the UTF-8 encoding of the source. Never a
#| character index and never a grapheme index — C<"\r\n"> is one Raku
#| grapheme and two bytes, so C<.chars> arithmetic and tree-sitter
#| offsets disagree the moment a file has Windows line endings.
enum InputEncoding is export (
    INPUT_ENCODING_UTF8     => 0,
    INPUT_ENCODING_UTF16_LE => 1,
    INPUT_ENCODING_UTF16_BE => 2,
    INPUT_ENCODING_CUSTOM   => 3,
);

#| Thrown when a tree-sitter query cannot be compiled, or when it
#| compiles but names a predicate L<TreeSitter::Native::Query> is not
#| willing to evaluate.
#|
#| Carries the machine-readable C<kind> (a C<QueryErrorKind>), the
#| C<offset> — a BYTE offset into the UTF-8 encoding of the query
#| source, per the byte doctrine — and the C<source> it was compiling,
#| from which the human-readable C<line>, C<column> and C<snippet> are
#| derived lazily.
#|
#|     use TreeSitter::Native::Query;
#|
#|     my $q = try Query.new('python', '(function_definition');
#|     given $! -> $err {
#|         say $err.kind;      # QUERY_ERROR_SYNTAX
#|         say $err.offset;    # 20
#|         say $err.line;      # 1
#|         say $err.column;    # 21   (1-based, in characters)
#|         say $err.message;
#|         # tree-sitter query error (syntax) at byte 20, line 1
#|         # column 21: (function_definition
#|     }
#|
#| C<column> and C<snippet> are the only two members expressed in
#| characters rather than bytes; they exist to be printed at a human,
#| and are computed by decoding the source up to C<offset>.
class X::TreeSitter::Query is Exception {
    has QueryErrorKind $.kind is required;
    has UInt           $.offset = 0;
    has Str            $.source = '';
    has Str            $.detail;

    #| Human-readable spelling of C<.kind>: "syntax", "node type",
    #| "field", "capture", "structure", "language", "predicate", or
    #| "none" — the words tree-sitter's own error messages use.
    method kind-description(--> Str) {
        # Indexed by the enum's integer value, which is the C ABI's own
        # ordering — a hash keyed by the enum values themselves would
        # trip the bareword-autoquote rule (`CONST => 'x'` makes the
        # literal string "CONST" the key, not the enum's).
        my constant @WORDS =
            'none', 'syntax', 'node type', 'field',
            'capture', 'structure', 'language', 'predicate';
        @WORDS[$!kind.value] // $!kind.key;
    }

    #| The source text preceding C<.offset>, decoded. Used to derive
    #| C<line> and C<column>; invalid UTF-8 before the offset degrades
    #| to the empty string rather than throwing out of an exception
    #| accessor.
    method !prefix(--> Str) {
        return '' unless $!source.chars && $!offset;
        my Blob $bytes = $!source.encode('utf-8');
        my UInt $cut   = $!offset min $bytes.elems;
        (try $bytes.subbuf(0, $cut).decode('utf-8')) // '';
    }

    #| 1-based line number of C<.offset> within the query source.
    method line(--> UInt) {
        self!prefix.comb("\n").elems + 1;
    }

    #| 1-based column of C<.offset> within its line, counted in
    #| characters — a display aid, not an offset you can feed back to
    #| tree-sitter. Use C<.offset> for that.
    method column(--> UInt) {
        my Str $prefix = self!prefix;
        my Int $nl     = $prefix.rindex("\n") // -1;
        $prefix.chars - $nl;
    }

    #| Up to 40 characters of the query source starting at C<.offset>,
    #| with newlines flattened — enough to recognise the pattern that
    #| went wrong without spilling a whole query into a log line.
    method snippet(--> Str) {
        return '' unless $!source.chars;
        my Blob $bytes = $!source.encode('utf-8');
        return '' if $!offset >= $bytes.elems;
        my Str $rest =
            (try $bytes.subbuf($!offset).decode('utf-8')) // '';
        my Str $head = $rest.substr(0, 40).subst("\n", ' ', :g).trim;
        $rest.chars > 40 ?? "$head…" !! $head;
    }

    method message(--> Str) {
        my Str $where = $!source.chars
            ?? " at byte $!offset, line {self.line} column {self.column}"
            !! " at byte $!offset";
        my Str $what = self.snippet.chars ?? ": {self.snippet}" !! '';
        my Str $why  = $!detail.defined && $!detail.chars
            ?? " — $!detail" !! '';
        "tree-sitter query error ({self.kind-description})$where$what$why";
    }
}
